version: "3.7"

volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres: {}

services:
  db:
    image: postgres:11.3
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always


  grafana:
    image: grafana/grafana:5.4.3
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
    restart: always
