global:
  scrape_interval: 15s

  external_labels:
    monitor: 'myapp'

scrape_configs:
  - job_name: 'monitoring-sandbox'
    scrape_interval: 5s

    static_configs:
      - targets: ['docker.for.mac.localhost:4000']
